### ISSUE TITLE
why long time not update?

### ISSUE THREAD

**Issue by mouday** [DormyMo/SpiderKeeper#119]
now , i use new tool: https://github.com/mouday/spider-admin-pro

**Comment by realtechspecs** [comment]
> now , i use new tool: https://github.com/mouday/spider-admin-pro

Is there an English version?

**Comment by mouday** [comment]
> > now , i use new tool: https://github.com/mouday/spider-admin-pro
> 
> Is there an English version?

i will support english soon...

**Comment by karlbaillie** [comment]
> > > now , i use new tool: https://github.com/mouday/spider-admin-pro
> > 
> > 
> > Is there an English version?
> 
> i will support english soon...

please do, would be very interested in this
