### ISSUE TITLE
加了个超长的args后，按钮飞出屏幕外了

### ISSUE THREAD

**Issue by seozed** [DormyMo/SpiderKeeper#18]
给爬虫传了一个由100多个关键词组成的字符串作为参数后。。。

页面布局跪了，参数那栏把修改、运行按钮撑出屏幕外了

![qq 20170420182031](https://cloud.githubusercontent.com/assets/4144227/25226145/6b647f88-25f6-11e7-9ecf-20c15495407b.png)

**Comment by seozed** [comment]
想删除都没地删;(

**Comment by DormyMo** [comment]
/project/1/job/15/remove

**Comment by seozed** [comment]
OK了
