### ISSUE TITLE
dashboard页面建议

### ISSUE THREAD

**Issue by seozed** [DormyMo/SpiderKeeper#21]
我在使用的过程中遇到一个问题：
有的时候，我需要修改已经部署的爬虫代码，当我重新上传新的egg文件覆盖原project时，SpiderKeeper会在数秒内显示无法显示最新的project爬虫，我猜是在更新:）

如下图：

![snipaste_20170428_111532](https://cloud.githubusercontent.com/assets/4144227/25513005/745cc17c-2c04-11e7-93d8-b1f34f5cfc89.png)

或许可以增加一点提示，显示该project最新的部署时间？

**Comment by DormyMo** [comment]
谢谢 @seozed  的建议

当提示信息deploy success，表示新的egg已经生效，

后续会考虑显示部署的工程版本(更新时间)
