### ISSUE TITLE
scrapyd-deploy 可以打包非.py文件吗

### ISSUE THREAD

**Issue by seozed** [DormyMo/SpiderKeeper#22]
有些配置我是写到txt文件里的，文件修改：比如账号信息、网址链接、搜索关键词列表……

发现用` scrapyd-deploy --build-egg output.egg`打包的时候，只对.py文件有效，可以把其它资源文件也打包进来吗

**Comment by DormyMo** [comment]
不支持 ，可使用资源文件的绝对路径

**Comment by seozed** [comment]
主要是生产环境和开发环境不同，不能用绝对路径。

我想到把关键词、账号一些配置写到.py里了

**Comment by Rockyzsu** [comment]
可以支持的。
