### ISSUE TITLE
关于定时任务功能

### ISSUE THREAD

**Issue by youngcraft** [DormyMo/SpiderKeeper#23]
消息提示 sqlite3 出现错误，错误信息如下：

  "code": 500, 
  "data": null, 
  "msg": "(sqlite3.IntegrityError) NOT NULL constraint failed: sk_job_execution.service_job_execution_id [SQL: u'INSERT INTO sk_job_execution (date_created, date_modified, project_id, service_job_execution_id, job_instance_id, create_time, start_time, end_time, running_status, running_on) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: (1,

请问这个问题如何解决

**Comment by DormyMo** [comment]
please start the scrapyd service first.
