### ISSUE TITLE
Help - how to debug spiderkeeper code?

### ISSUE THREAD

**Issue by appleboy1977** [DormyMo/SpiderKeeper#24]
I downloaded the code from main branch and try to debug in pycharm. however it seems always run from the pip installed spiderkeeper in dist package.
How can i debug the downloaded code? Thanks,

**Comment by DormyMo** [comment]
you can uninstall spiderkeeper which installed by pip,then debug it.

**Comment by appleboy1977** [comment]
Thanks, I will try it. Thanks for the great work.:)

**Comment by appleboy1977** [comment]
In console, cannot run

[root@zcyq-collect-02 SpiderKeeper]# pwd
/root/SpiderKeeper/SpiderKeeper
[root@zcyq-collect-02 SpiderKeeper]# ll
总用量 40
drwx------. 8 root root  4096 5月  16 21:42 app
-rw-------. 1 root root   969 5月  16 21:42 config.py
-rw-------. 1 root root   802 5月  16 21:42 config.pyc
-rw-------. 1 root root    46 5月  16 21:42 __init__.py
-rw-------. 1 root root   205 5月  16 21:42 __init__.pyc
-rw-------. 1 root root  2961 5月  16 21:42 run.py
-rw-------. 1 root root 14336 5月  16 21:42 SpiderKeeper.db
[root@zcyq-collect-02 SpiderKeeper]# nano run.py 
[root@zcyq-collect-02 SpiderKeeper]# python ./run.py
Traceback (most recent call last):
  File "./run.py", line 6, in <module>
    from SpiderKeeper.app import app, initialize
ImportError: No module named SpiderKeeper.app
[root@zcyq-collect-02 SpiderKeeper]#
