### ISSUE TITLE
In console, cannot run spiderkeeper.

### ISSUE THREAD

**Issue by appleboy1977** [DormyMo/SpiderKeeper#25]
I wanna run the main branch code in console,  git clone and
in console, cannot run. Here's the screen log,

[root@zcyq-collect-02 SpiderKeeper]# pwd
/root/SpiderKeeper/SpiderKeeper
[root@zcyq-collect-02 SpiderKeeper]# ll
总用量 40
drwx------. 8 root root 4096 5月 16 21:42 app
-rw-------. 1 root root 969 5月 16 21:42 config.py
-rw-------. 1 root root 802 5月 16 21:42 config.pyc
-rw-------. 1 root root 46 5月 16 21:42 init.py
-rw-------. 1 root root 205 5月 16 21:42 init.pyc
-rw-------. 1 root root 2961 5月 16 21:42 run.py
-rw-------. 1 root root 14336 5月 16 21:42 SpiderKeeper.db
[root@zcyq-collect-02 SpiderKeeper]# nano run.py
[root@zcyq-collect-02 SpiderKeeper]# python ./run.py
Traceback (most recent call last):
File "./run.py", line 6, in 
from SpiderKeeper.app import app, initialize
ImportError: No module named SpiderKeeper.app
[root@zcyq-collect-02 SpiderKeeper]#

**Comment by appleboy1977** [comment]
i pip installed spiderkeeper and uninstall it, the error still there.

**Comment by DormyMo** [comment]
`cd SpiderKeeper`
`export PYTHONPATH=$PYTHONPATH:./`
`python SpiderKeeper/run.py`
