### ISSUE TITLE
同时可运行的爬虫数量

### ISSUE THREAD

**Issue by Lving** [DormyMo/SpiderKeeper#31]
作者你好， 请问spiderkeeper只能同时运行4个爬虫吗？ 如果我想运行更多的爬虫项目，能否在设置中进行更改？

**Comment by Lving** [comment]
I have found the solutions 
>> **max_proc_per_cpu**
>>The maximum number of concurrent Scrapy process that will be started per cpu. Defaults to 4.

**Comment by DormyMo** [comment]
恩配置scrpayd的配置文件即可
