### ISSUE TITLE
无法提交部署以及删除项目

### ISSUE THREAD

**Issue by Jane620** [DormyMo/SpiderKeeper#49]
控制台一直报错，
Execution of job "sync_job_execution_status_job (trigger: interval[0:00:05], next run at: 2017-10-26 16:51:06 CST)" skipped: maximum number of running instances reached (1)
重启spiderkeeper以及scrapyd服务还是这个情况

**Comment by DormyMo** [comment]
检查sk所在机器网络是否能正常连接scrapyd

**Comment by keyboardWitch** [comment]
我也遇到这样的情况。其实 绕过spiderkeeper，直接向scrapyd提交一个递归爬虫，scrapyd就会僵死在那里。是不是有什么多进程的设置？
