### ISSUE TITLE
如果spiderkeeper和scrpayd不在同一台机子上怎么连接呢？

### ISSUE THREAD

**Issue by ap1024** [DormyMo/SpiderKeeper#54]
spiderkeeper是一台机子
scrapyd 有可能是台机子使用了nginx配置，
spiderkeeper怎么使用用户名和密码连接scrapyd呢？

**Comment by DormyMo** [comment]
使用启动参数 --server 
需要验证的scrapyd暂不支持

**Comment by ap1024** [comment]
我看链接方式你是单独写的接口，没有使用scrapyd api.
有一个api接口，可以使用用户名和密码链接的；
def __init__(self, target='http://localhost:6800', auth=None,
                 endpoints=None, client=None):
        """
        Instantiates the ScrapydAPI wrapper for use.
        Args:
          target (str): the hostname/port to hit with requests.
          auth (str, str): a 2-item tuple containing user/pass details. Only
                           used when `client` is not passed.
          endpoints: a dictionary of custom endpoints to apply on top of
                     the pre-existing defaults.
          client: a pre-instantiated requests-like client. By default, we use
                  our own client. Override for your own needs.
;
你这一版本非常不错，只是如果多台机子管理，最好是可以自定义服务器地址和用户名密码登陆。
这样就方便管理。
谢谢你的回复

**Comment by ileadall42** [comment]
这个很不错呀
