### ISSUE TITLE
can  not upload egg file

### ISSUE THREAD

**Issue by danerlt** [DormyMo/SpiderKeeper#67]
error info:
{
  "code": 500, 
  "data": null, 
  "msg": "HTTPConnectionPool(host='localhost', port=6800): Max retries exceeded with url: /addversion.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x02C33C30>: Failed to establish a new connection: [WinError 10061] \u7531\u4e8e\u76ee\u6807\u8ba1\u7b97\u673a\u79ef\u6781\u62d2\u7edd\uff0c\u65e0\u6cd5\u8fde\u63a5\u3002',))", 
  "success": false
}

unicode info:
由于目标计算机积极拒绝，无法连接。

**Comment by Lving** [comment]
this error is not caused by spiderkeeper, please check the computer firewall

**Comment by hchen-markettrack** [comment]
@Lt-grint @DormyMo @Lving 
I met same error, do you know how to fix it?
```
{
  "code": 500, 
  "data": null, 
  "msg": "HTTPConnectionPool(host='0.0.0.0', port=6800): Max retries exceeded with url: /addversion.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x10536fe48>: Failed to establish a new connection: [Errno 61] Connection refused',))", 
  "success": false
}
```

**Comment by tede12** [comment]
I have same error (I stopped before network firewall). Anyone solve the error?
