### ISSUE TITLE
spiderkeeper最多能监控多少台服务器的多少个爬虫？在哪里可以修改？

### ISSUE THREAD

**Issue by SimonWang00** [DormyMo/SpiderKeeper#71]
我的将50个分布式爬虫上传部署在10台服务器上，提示超过了最大监控数，该如何设置呢？谢谢解答！

![max](https://user-images.githubusercontent.com/37493968/41694182-a04c6658-753b-11e8-86be-b180edcc6448.png)

**Comment by SimonWang00** [comment]
How many crawlers can spiderkeeper monitor at most? Where can I modify it? @DormyMo

**Comment by DormyMo** [comment]
[https://github.com/DormyMo/SpiderKeeper/blob/master/SpiderKeeper/app/__init__.py#L111](https://github.com/DormyMo/SpiderKeeper/blob/master/SpiderKeeper/app/__init__.py#L111)   increase the interval

**Comment by DormyMo** [comment]
原因是同步爬虫状态是一个5s的定时任务，需监控的服务太多导致同步状态时间较长，导致的
