### ISSUE TITLE
不支持 setting，例如 setting=CONCURRENT_REQUESTS=40

### ISSUE THREAD

**Issue by zamzus** [DormyMo/SpiderKeeper#88]
会报错
{
  "code": 500, 
  "data": null, 
  "msg": "dictionary update sequence element #0 has length 3; 2 is required", 
  "success": false
}

**Comment by Ericliu68** [comment]
这个错误是你上传egg包以后，scrapyd没有读取到spiders，scrapyd会对egg包解析判断是否可以正常运行，有错误的话，不会出现新的egg里面的spider，在spiderkeeper请求这个job的时候，scrapyd里面是空的，所以spiderkeeper会显示这个log，上传的时候看着点scrapyd运行的提示 。
看一下https://github.com/DormyMo/SpiderKeeper/issues/87，里面有两位大神根据这个问题的修改

**Comment by zamzus** [comment]
有读取到spiders的，试过很多次了，不添加 setting=CONCURRENT_REQUESTS=40 是可以执行的，一但添加了  setting=CONCURRENT_REQUESTS=40 这个就出现上面的错误了

**Comment by Ericliu68** [comment]
你在上传一次，你去看看scrapyd，curl看看project有spiders吗

**Comment by zamzus** [comment]
哈哈，有的，我每天都在定时运行的持续了好几个月的项目了。以前没有试过添加 setting 参数，最近是因为数据量太大了，想把控一下时间就添加了 setting=CLOSESPIDER_TIMEOUT=40000，发现出现上述错误，之后试了 setting=CONCURRENT_REQUESTS=40 和其他 setting 也是一样的错误，现在依然是不填加 setting 来执行这个爬虫的

**Comment by zamzus** [comment]
好像作者没有考虑到对 setting=xxxx=xxx 做处理，看了源码是没有，嗯，不支持 setting=xxxx=xxx，只能在爬虫内调用 crawler 来设置了

**Comment by my8100** [comment]
You could use [ScrapydWeb](https://github.com/my8100/scrapydweb) before the issue is fixed.

**Comment by Ericliu68** [comment]
spiderkeeper只是一个爬虫调度器,运行爬虫的是scrapyd,setting这个配置没有效果,可以查看scrapyd的相关操作,至于为什么数值弄这么大,我觉得还是要看看最新的scrapy的官方文档

**Comment by iamumairayub** [comment]
I also want to pass custom setting but its not supported :(
