### ISSUE TITLE
80个同样时间的定时任务，每次到时间只跑9个，请大神解决！！！！！！！！

### ISSUE THREAD

**Issue by ocyisheng** [DormyMo/SpiderKeeper#96]
80个同样时间的定时任务，每次到时间只跑9个，请大神解决！！！！！！！！
![9fecc4a0bc142d47a13745a5faea9f06](https://user-images.githubusercontent.com/16376374/53154374-9c79d300-35f5-11e9-80d1-9caeed4a6b19.png)
上边是任务执行部分

![55bd3d0dbd94ace393e56ba048af9d43](https://user-images.githubusercontent.com/16376374/53154464-ce8b3500-35f5-11e9-8237-052dff01cf45.png)
这个是定时任务，运行周期设置情况

请告知怎么解决？？

**Comment by my8100** [comment]
You could use [ScrapydWeb](https://github.com/my8100/scrapydweb) before the issue is fixed.

**Comment by ocyisheng** [comment]
@my8100 Hi,Lao Tie.
Thank you for your reply。
I have solved this problem。
Resetting scrapyd settings max_proc parameter is solved。
May you are SpiderMan？
