### ISSUE TITLE
SpiderKeeper 运行任务阻塞在Next Jobs 中，影响到后面的任务定时执行计划无法执行

### ISSUE THREAD

**Issue by MingCrash** [DormyMo/SpiderKeeper#99]

**Comment by my8100** [comment]
You could use [ScrapydWeb](https://github.com/my8100/scrapydweb) before the issue is fixed.

**Comment by MingCrash** [comment]
問題自己找到了，不關spiderkeeper的事，是相關任務的scrapyd服務崩潰了，所以任務滯留在next job隊列
